import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import Head from "next/head";
import LeftSide from "@/components/Leftside";
import About from "@/components/About";
import Banner from "@/components/Banner";
import RightSide from "@/components/RightSide";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Alec Jericho Sim</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-bodyFont w-full h-screen bg-bodyColor text-textLight overflow-x-hidden overflow-y-scroll scrollbar scrollbar-track-textDark/20 scrollbar-thumb-textDark/60">
        <Navbar />
        <div className="w-full h-[88vh] xl:flex items-center gap-20 justify-between">
          <div className="w-32 h-full">
            <LeftSide />
          </div>
          <div className="w-full h-[88vh] overflow-y-scroll scrollbarHide">
            <Banner />
            <About />
          </div>
          <div className="w-32 h-full">
            <RightSide />
          </div>
        </div>
      </main>
    </>
  );
}
